CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    gender VARCHAR(10) NOT NULL,
    birthday DATA NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL,
    create_at TIMESTAMP WITH TIME ZONE DEFAULD CURRENT_TIMESTAMP
);
